"""Add settings table

Revision ID: f180f7bf6d2c
Revises: 930fa663493d
Create Date: 2026-02-01 05:25:06.062312

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f180f7bf6d2c"
down_revision = "930fa663493d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(
        op.f("ix_settings_category"), "settings", ["category"], unique=False
    )
    op.create_index(op.f("ix_settings_key"), "settings", ["key"], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_settings_key"), table_name="settings")
    op.drop_index(op.f("ix_settings_category"), table_name="settings")
    op.drop_table("settings")
    # ### end Alembic commands ###
