"""Add Membership Plans

Revision ID: 930fa663493d
Revises: 001
Create Date: 2026-01-30 23:47:32.881125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930fa663493d'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_constraint('biometric_templates_member_id_key', 'biometric_templates', type_='unique')
    # op.drop_index('ix_biometric_templates_member_id', table_name='biometric_templates')
    # op.create_index(op.f('ix_biometric_templates_member_id'), 'biometric_templates', ['member_id'], unique=True)
    # op.drop_constraint('cameras_name_key', 'cameras', type_='unique')
    # op.drop_index('ix_cameras_name', table_name='cameras')
    # op.create_index(op.f('ix_cameras_name'), 'cameras', ['name'], unique=True)
    # op.drop_constraint('members_email_key', 'members', type_='unique')
    # op.drop_index('ix_members_email', table_name='members')
    # op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=True)
    # op.drop_constraint('fk_members_biometric_template_id', 'members', type_='foreignkey')
    # op.drop_column('members', 'biometric_template_id')
    op.add_column('memberships', sa.Column('plan_id', sa.UUID(), nullable=True))
    op.alter_column('memberships', 'type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_foreign_key(None, 'memberships', 'membership_plans', ['plan_id'], ['id'])
    # op.drop_constraint('sales_transactions_invoice_number_key', 'sales_transactions', type_='unique')
    # op.drop_index('ix_sales_transactions_invoice_number', table_name='sales_transactions')
    # op.create_index(op.f('ix_sales_transactions_invoice_number'), 'sales_transactions', ['invoice_number'], unique=True)
    # op.create_index(op.f('ix_sales_transactions_invoice_number'), 'sales_transactions', ['invoice_number'], unique=True)
    # Skipped users table changes to avoid conflicts
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'is_active',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'STAFF', name='userrole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_sales_transactions_invoice_number'), table_name='sales_transactions')
    op.create_index('ix_sales_transactions_invoice_number', 'sales_transactions', ['invoice_number'], unique=False)
    op.create_unique_constraint('sales_transactions_invoice_number_key', 'sales_transactions', ['invoice_number'])
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.alter_column('memberships', 'type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('memberships', 'plan_id')
    op.add_column('members', sa.Column('biometric_template_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_members_biometric_template_id', 'members', 'biometric_templates', ['biometric_template_id'], ['id'])
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.create_index('ix_members_email', 'members', ['email'], unique=False)
    op.create_unique_constraint('members_email_key', 'members', ['email'])
    op.drop_index(op.f('ix_cameras_name'), table_name='cameras')
    op.create_index('ix_cameras_name', 'cameras', ['name'], unique=False)
    op.create_unique_constraint('cameras_name_key', 'cameras', ['name'])
    op.drop_index(op.f('ix_biometric_templates_member_id'), table_name='biometric_templates')
    op.create_index('ix_biometric_templates_member_id', 'biometric_templates', ['member_id'], unique=False)
    op.create_unique_constraint('biometric_templates_member_id_key', 'biometric_templates', ['member_id'])
    op.drop_table('membership_plans')
    # ### end Alembic commands ###
