#!/bin/bash
# =============================================================================
# FaceGYM Phase 1 Security Hardening — Run on PRODUCTION SERVER
# =============================================================================
# This script addresses the CRITICAL findings from the pentest report:
#   VULN-004: CVE-2024-6387 (regreSSHion SSH RCE)
#   VULN-014: Weak SSH MAC algorithm (hmac-sha1)
#   VULN-020: SSH weak key exchange parameters
#   Network: Block external access to ports 8000/8001
# =============================================================================
# USAGE: sudo bash scripts/security-harden-phase1.sh
# =============================================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${RED}======================================================${NC}"
echo -e "${RED}  FaceGYM Phase 1 — CRITICAL Security Hardening${NC}"
echo -e "${RED}======================================================${NC}"
echo ""

# ---------------------------------------------------------------------------
# 1. PATCH SSH — CVE-2024-6387 (regreSSHion)
# ---------------------------------------------------------------------------
echo -e "${YELLOW}[1/5] Patching OpenSSH (CVE-2024-6387)...${NC}"
CURRENT_SSH_VERSION=$(ssh -V 2>&1 | grep -oP 'OpenSSH_\K[0-9.]+')
echo "  Current OpenSSH version: $CURRENT_SSH_VERSION"

apt update && apt install -y openssh-server
NEW_VERSION=$(ssh -V 2>&1 | grep -oP 'OpenSSH_\K[0-9.]+')
echo -e "  ${GREEN}Updated OpenSSH to: $NEW_VERSION${NC}"

# ---------------------------------------------------------------------------
# 2. HARDEN SSH CONFIGURATION
# ---------------------------------------------------------------------------
echo -e "${YELLOW}[2/5] Hardening SSH configuration...${NC}"

# Backup current config
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.pre-hardening.$(date +%Y%m%d%H%M%S)

# Create a hardening drop-in config (safer than editing main config)
cat > /etc/ssh/sshd_config.d/99-facegym-hardening.conf << 'EOF'
# FaceGYM Security Hardening — Phase 1
# Generated by security-harden-phase1.sh

# Disable weak MAC algorithms (VULN-014)
MACs hmac-sha2-512,hmac-sha2-256

# Use modern key exchange only (VULN-020)
KexAlgorithms curve25519-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512

# Disable weak ciphers
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

# Disable root login
PermitRootLogin no

# Disable password authentication (key-only)
PasswordAuthentication no

# Disable empty passwords
PermitEmptyPasswords no

# Limit max auth attempts
MaxAuthTries 3

# Set login grace timeout (mitigates brute force)
LoginGraceTime 30

# Disable unused features
X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no
EOF

echo -e "  ${GREEN}Created /etc/ssh/sshd_config.d/99-facegym-hardening.conf${NC}"

# Validate config before restarting
sshd -t
if [ $? -eq 0 ]; then
    systemctl restart sshd
    echo -e "  ${GREEN}SSH config validated and restarted successfully${NC}"
else
    echo -e "  ${RED}ERROR: SSH config validation failed! NOT restarting.${NC}"
    echo "  Run 'sshd -t' to debug."
    exit 1
fi

# ---------------------------------------------------------------------------
# 3. FIREWALL — Block external access to ports 8000/8001
# ---------------------------------------------------------------------------
echo -e "${YELLOW}[3/5] Configuring firewall (blocking ports 8000/8001)...${NC}"

# Check if ufw is available
if command -v ufw &> /dev/null; then
    # Allow essential services first
    ufw allow 22/tcp comment 'SSH'
    ufw allow 80/tcp comment 'HTTP (nginx)'
    ufw allow 443/tcp comment 'HTTPS (nginx)'

    # Explicitly deny direct access to backend/CV service
    # These should ONLY be accessible via nginx reverse proxy (localhost)
    ufw deny 8000/tcp comment 'Backend API — internal only'
    ufw deny 8001/tcp comment 'CV Service — internal only'

    # Also deny PostgreSQL and Redis from external
    ufw deny 5432/tcp comment 'PostgreSQL — internal only'
    ufw deny 6379/tcp comment 'Redis — internal only'

    # Enable firewall (may disrupt existing connections, warn user)
    echo -e "  ${YELLOW}About to enable UFW firewall. Make sure you have SSH access!${NC}"
    echo "  Ports allowed: 22 (SSH), 80 (HTTP), 443 (HTTPS)"
    echo "  Ports blocked: 8000, 8001, 5432, 6379"
    read -p "  Continue? (yes/no): " CONFIRM
    if [ "$CONFIRM" = "yes" ]; then
        echo "y" | ufw enable
        echo -e "  ${GREEN}UFW firewall enabled${NC}"
        ufw status verbose
    else
        echo -e "  ${YELLOW}Skipped UFW enable. Run 'ufw enable' manually when ready.${NC}"
    fi
else
    # Fallback to iptables
    echo "  UFW not found, using iptables directly..."
    
    # Block external access to backend/CV service ports
    # Allow from localhost only
    iptables -A INPUT -p tcp --dport 8000 -s 127.0.0.1 -j ACCEPT
    iptables -A INPUT -p tcp --dport 8000 -j DROP
    iptables -A INPUT -p tcp --dport 8001 -s 127.0.0.1 -j ACCEPT
    iptables -A INPUT -p tcp --dport 8001 -j DROP
    
    # Also protect DB and Redis
    iptables -A INPUT -p tcp --dport 5432 -s 127.0.0.1 -j ACCEPT
    iptables -A INPUT -p tcp --dport 5432 -j DROP
    iptables -A INPUT -p tcp --dport 6379 -s 127.0.0.1 -j ACCEPT
    iptables -A INPUT -p tcp --dport 6379 -j DROP
    
    # Save rules
    if command -v iptables-save &> /dev/null; then
        iptables-save > /etc/iptables.rules
        echo -e "  ${GREEN}iptables rules saved to /etc/iptables.rules${NC}"
    fi
    
    echo -e "  ${YELLOW}WARNING: iptables rules are NOT persistent across reboots.${NC}"
    echo "  Install 'iptables-persistent' or add to system startup scripts."
fi

# ---------------------------------------------------------------------------
# 4. GENERATE INTERNAL API SECRET
# ---------------------------------------------------------------------------
echo -e "${YELLOW}[4/5] Generating internal API secret...${NC}"
INTERNAL_SECRET=$(openssl rand -hex 32)
CV_API_KEY=$(openssl rand -hex 32)

echo ""
echo -e "  ${GREEN}Generated secrets — ADD THESE TO YOUR .env FILES:${NC}"
echo ""
echo "  # In BOTH backend/.env AND cv_service/.env:"
echo "  INTERNAL_API_SECRET=$INTERNAL_SECRET"
echo ""
echo "  # In cv_service/.env only:"
echo "  API_KEY=$CV_API_KEY"
echo ""

# ---------------------------------------------------------------------------
# 5. VERIFY
# ---------------------------------------------------------------------------
echo -e "${YELLOW}[5/5] Running verification...${NC}"

echo ""
echo "  Checking SSH version..."
ssh -V 2>&1

echo ""
echo "  Checking SSH config..."
sshd -T | grep -E "macs|kexalgorithms|ciphers|permitrootlogin|passwordauthentication" || true

echo ""
echo "  Checking firewall..."
if command -v ufw &> /dev/null; then
    ufw status | head -20
else
    iptables -L INPUT -n --line-numbers | grep -E "8000|8001|5432|6379" || true
fi

echo ""
echo -e "${GREEN}======================================================${NC}"
echo -e "${GREEN}  Phase 1 Hardening COMPLETE${NC}"
echo -e "${GREEN}======================================================${NC}"
echo ""
echo "  REMAINING STEPS (manual):"
echo "  1. Add INTERNAL_API_SECRET to backend/.env and cv_service/.env"
echo "  2. Add API_KEY to cv_service/.env"
echo "  3. Restart backend and CV service"
echo "  4. Verify: curl http://localhost:8001/health (should require API key)"
echo "  5. Verify: curl http://localhost:8000/api/cv/templates (should require secret)"
echo "  6. Verify: from EXTERNAL machine, ports 8000/8001 should be unreachable"
echo ""
